name: MathUtils CI Pipeline

on:
  - push

jobs:
  say-hello:
    name: Say Hello

       runs-on: ubuntu-latest

    steps:
      
      - name: Print greeting
        run: echo "Hello, GitHub Actions! The app is Math Utils"

      - name: Print date and time
        run: date

      - name: Print system information
        run: |
          echo "Running on:"
          uname -a

